In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


Library Numpy => Olah Numerik di Pypton Library Pandas => Untuk import external file csv,clsx,txt......

In [ ]:
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Grape' 66.0 62000.0]
 ['Pineapple' 37.0 38000.0]
 ['Apple' 40.0 34000.0]
 ['Carrot' 48.0 31000.0]
 ['Pineapple' 50.0 nan]
 ['Grape' 45.0 38000.0]
 ['Carrot' nan 42000.0]
 ['Apple' 58.0 69000.0]
 ['Pineapple' 60.0 73000.0]
 ['Apple' 47.0 57000.0]
 ['Carrot' 30.0 nan]
 ['Grape' 65.0 48000.0]
 ['Pineapple' nan 52000.0]
 ['Apple' 57.0 65000.0]
 ['Grape' 77.0 78000.0]
 ['Carrot' 45.0 47000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Grape' 66.0 62000.0]
 ['Pineapple' 37.0 38000.0]
 ['Apple' 40.0 34000.0]
 ['Carrot' 48.0 31000.0]
 ['Pineapple' 50.0 52428.57142857143]
 ['Grape' 45.0 38000.0]
 ['Carrot' 51.785714285714285 42000.0]
 ['Apple' 58.0 69000.0]
 ['Pineapple' 60.0 73000.0]
 ['Apple' 47.0 57000.0]
 ['Carrot' 30.0 52428.57142857143]
 ['Grape' 65.0 48000.0]
 ['Pineapple' 51.785714285714285 52000.0]
 ['Apple' 57.0 65000.0]
 ['Grape' 77.0 78000.0]
 ['Carrot' 45.0 47000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 0.0 1.0 0.0 66.0 62000.0]
 [0.0 0.0 0.0 1.0 37.0 38000.0]
 [1.0 0.0 0.0 0.0 40.0 34000.0]
 [0.0 1.0 0.0 0.0 48.0 31000.0]
 [0.0 0.0 0.0 1.0 50.0 52428.57142857143]
 [0.0 0.0 1.0 0.0 45.0 38000.0]
 [0.0 1.0 0.0 0.0 51.785714285714285 42000.0]
 [1.0 0.0 0.0 0.0 58.0 69000.0]
 [0.0 0.0 0.0 1.0 60.0 73000.0]
 [1.0 0.0 0.0 0.0 47.0 57000.0]
 [0.0 1.0 0.0 0.0 30.0 52428.57142857143]
 [0.0 0.0 1.0 0.0 65.0 48000.0]
 [0.0 0.0 0.0 1.0 51.785714285714285 52000.0]
 [1.0 0.0 0.0 0.0 57.0 65000.0]
 [0.0 0.0 1.0 0.0 77.0 78000.0]
 [0.0 1.0 0.0 0.0 45.0 47000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 0 1 0 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)


In [ ]:
print(x_train)

[[0.0 1.0 0.0 0.0 51.785714285714285 42000.0]
 [0.0 1.0 0.0 0.0 30.0 52428.57142857143]
 [0.0 0.0 0.0 1.0 50.0 52428.57142857143]
 [0.0 0.0 0.0 1.0 37.0 38000.0]
 [0.0 0.0 1.0 0.0 77.0 78000.0]
 [0.0 0.0 1.0 0.0 66.0 62000.0]
 [0.0 1.0 0.0 0.0 45.0 47000.0]
 [1.0 0.0 0.0 0.0 47.0 57000.0]
 [0.0 0.0 0.0 1.0 60.0 73000.0]
 [0.0 0.0 0.0 1.0 51.785714285714285 52000.0]
 [0.0 0.0 1.0 0.0 65.0 48000.0]
 [0.0 0.0 1.0 0.0 45.0 38000.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 0.0 48.0 31000.0]
 [1.0 0.0 0.0 0.0 57.0 65000.0]
 [1.0 0.0 0.0 0.0 58.0 69000.0]
 [1.0 0.0 0.0 0.0 40.0 34000.0]]


In [ ]:
print(y_train)

[0 1 1 1 0 0 1 1 0 1 0 1]


In [ ]:
print(y_test)

[0 0 1 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 1.0 0.0 -0.7071067811865475 -0.027510059182259322
  -0.936323455089873]
 [0.0 1.0 0.0 -0.7071067811865475 -1.7634896558558664
  -0.07384254377680403]
 [0.0 0.0 0.0 1.4142135623730951 -0.16980346874566968
  -0.07384254377680403]
 [0.0 0.0 0.0 1.4142135623730951 -1.2056994903672975 -1.2671380512099544]
 [0.0 0.0 1.0 -0.7071067811865475 1.981672883853096 2.0410079099908587]
 [0.0 0.0 1.0 -0.7071067811865475 1.1051454809424877 0.7177495255105335]
 [0.0 1.0 0.0 -0.7071067811865475 -0.5682250155232189 -0.5228052099397714]
 [1.0 0.0 0.0 -0.7071067811865475 -0.4088563968121992 0.30423128036043184]
 [0.0 0.0 0.0 1.4142135623730951 0.6270396248094288 1.627489664840757]
 [0.0 0.0 0.0 1.4142135623730951 -0.027510059182259322
  -0.1092869647896698]
 [0.0 0.0 1.0 -0.7071067811865475 1.025461171586978 -0.4401015609097511]
 [0.0 0.0 1.0 -0.7071067811865475 -0.5682250155232189 -1.2671380512099544]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -0.7071067811865475 -0.32917208745668936
  -1.8460635944200967]
 [1.0 0.0 0.0 -0.7071067811865475 0.3879866967428992 0.9658604726005945]
 [1.0 0.0 0.0 -0.7071067811865475 0.46767100609840906 1.2966750687206758]
 [1.0 0.0 0.0 -0.7071067811865475 -0.9666465623007681 -1.5979526473300356]]
